//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int idRes { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string TypeAccount { get; set; }
        public int idAccout { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
